name: Fix PHP code style issues

on:
  pull_request:
    paths:
      - "**.php"
      - ".github/workflows/fix-php-code-style-issues.yml"

permissions:
  contents: write

jobs:
  detect_php_changes:
    name: Detect Changes in PHP Files
    runs-on: ubuntu-latest

    outputs:
      php_files_changed: ${{ steps.filter.outputs.php_files }}

    steps:
      - name: Identify Changed PHP Files
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            php_files:
              - added|modified: '**/*.php'

  php-code-styling:
    name: Fix PHP Code Styling
    needs: detect_php_changes
    if: ${{ needs.detect_php_changes.outputs.php_files_changed == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.5

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Fix styling
